
version: '3.7'
services:
  database:
    container_name: db_arriendos_container
    restart: always
    image: mysql:5.7  #mysql:5.7
    environment:
      MYSQL_DATABASE: 'db_arriendos'              # name of database
      MYSQL_USER: 'edward'                # sample is the name of user
      MYSQL_PASSWORD: 'admin'          # password for sample user
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
    volumes:
      - arriendos_vl:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  arriendos_vl:
    driver: local