spring:
  application-name: alquiler_api
  datasource:
    url: jdbc:mysql://localhost:3306/db_arriendos?currentSchema=true
    username: root
    password: rootpassword
    driver-class: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /api_arriendos