spring:
  application-name: alquiler_api
  datasource:
    url: jdbc:postgresql://localhost:5432/db_arriendo?currentSchema=true
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true