spring:
  application-name: alquiler_api
  datasource:
    url: jdbc:mysql://localhost:3306/db_arriendos?currentSchema=true
    username: edward
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true